name: ezy_di
description: Dependency Injection Tools for Dart
version: 0.0.2
repository: https://github.com/necessarylion/ezy-di
homepage: https://github.com/necessarylion/ezy-di

environment:
  sdk: '>=2.19.0 <3.0.0'

dev_dependencies:
  test: ^1.21.0
