name: Publish plugin

on:
  release:
    types: [created]

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
        
      - name: 'Dart pub publish'
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: ${{ secrets.DART_CREDENTIAL }}
          flutter: false
          skipTests: false
          force: true
          suppressBuildRunner: true
