name: Test plugin

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
        
      - name: 'Test plugin'
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: ${{ secrets.DART_CREDENTIAL }}
          flutter: false
          suppressBuildRunner: true
          testRunOnly: true
