name: Publish plugin

on:
  push:

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
        
      - name: 'Flutter pub publish'
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          flutter: false
          suppressBuildRunner: true
          testRunOnly: true
